# theme = "tokyonight"
# theme = "catppuccin_frappe"
# theme = "catppuccin_macchiato"
theme = "catppuccin_mocha"
# theme = "nord"

[editor]
# Makes the selection too hard to see
# cursorline = true
auto-format = false
# Show mode indicator in color
color-modes = true
# Disable pop-ups for multi-key commands
auto-info = false
rulers = [80]
auto-pairs = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.whitespace.render]
tab = "all"

[keys.insert]
C-v = ":clipboard-paste-before"

[keys.normal]
# Can't use these because you'd also have to override `d` which doesn't seem possible?
# y = ":clipboard-yank"
# p = ":clipboard-paste-after"
# P = ":clipboard-paste-before"
# R = ":clipboard-paste-replace"
# Probably not worth maintaining these? If I do, we need to also support
# extending the selection if it's present
# "{" = "goto_prev_paragraph"
# "}" = "goto_next_paragraph"
Z = { Q = ":quit!", Z = ":x" }
# Note `rotate_view` doesn't actually goes to the next view, not the previous
C-w = { c = "wclose", W = "rotate_view" }
A-S = "split_selection_on_newline"
C-s = "split_selection_on_newline"
# More consistent to use the default binding (shift bindings work on workplace)
# space = { f = "file_picker_in_current_directory" }
# Messes with multiple cursors pasting
# p = ":clipboard-paste-after"
# P = ":clipboard-paste-before"
# y = ":clipboard-yank-join"
# Y = ":clipboard-yank"
# R = ":clipboard-paste-replace"
# d = [":clipboard-yank-join", "delete_selection"]

# [keys.select]
# p = ":clipboard-paste-after"
# P = ":clipboard-paste-before"
# y = ":clipboard-yank-join"
# Y = ":clipboard-yank"
# R = ":clipboard-paste-replace"
# d = [":clipboard-yank-join", "delete_selection"]
