# theme = "tokyonight"
# theme = "catppuccin_frappe"
# theme = "catppuccin_macchiato"
theme = "nord"

[editor]
cursorline = true
auto-format = false
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
y = ":clipboard-yank"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
Z = { Q = ":quit!", Z = ":x" }
C-w = { c = "wclose" }
