shell:
  program: /usr/local/bin/fish

window:
  dimensions:
    columns: 80
    lines: 48

font:
  normal:
    family: "JetBrains Mono"
  size: 13.0

alt_send_esc: false

env:
  # Colors in `vim` don't work without setting `xterm-256color`
  TERM: xterm-256color

import:
  -  ~/.config/alacritty/modifiers.yml
  -  ~/.config/alacritty/theme.yml
