shell:
  program: /usr/local/bin/fish

window:
  dimensions:
    columns: 80
    lines: 48

font:
  normal:
    family: "JetBrains Mono"
  size: 13.0

alt_send_esc: false

import:
  -  ~/.config/alacritty/modifiers.yml
  -  ~/.config/alacritty/theme.yml
