shell:
  program: /usr/local/bin/fish

window:
  dimensions:
    columns: 80
    lines: 48
  decorations: "None"

font:
  normal:
    family: "JetBrains Mono"
  size: 13.0

env:
  ALACRITTY: "1"
  # Colors in `vim` don't work without setting `xterm-256color`
  TERM: xterm-256color

style:
  blinking: Off

import:
  -  ~/.config/alacritty/modifiers.yml
  -  ~/.config/alacritty/robenkleene.yml
  # -  ~/.config/alacritty/tokyo-night.yml

selection:
  save_to_clipboard: false
