key_bindings:
  - { key: A,         mods: Alt,       chars: "\x10a"                       }
  - { key: B,         mods: Alt,       chars: "\x10b"                       }
  - { key: C,         mods: Alt,       chars: "\x10c"                       }
  - { key: D,         mods: Alt,       chars: "\x10d"                       }
  - { key: E,         mods: Alt,       chars: "\x10e"                       }
  - { key: F,         mods: Alt,       chars: "\x10f"                       }
  - { key: G,         mods: Alt,       chars: "\x10g"                       }
  - { key: H,         mods: Alt,       chars: "\x10h"                       }
  - { key: I,         mods: Alt,       chars: "\x10i"                       }
  - { key: J,         mods: Alt,       chars: "\x10j"                       }
  - { key: K,         mods: Alt,       chars: "\x10k"                       }
  - { key: L,         mods: Alt,       chars: "\x10l"                       }
  - { key: M,         mods: Alt,       chars: "\x10m"                       }
  - { key: N,         mods: Alt,       chars: "\x10n"                       }
  - { key: O,         mods: Alt,       chars: "\x10o"                       }
  - { key: P,         mods: Alt,       chars: "\x10p"                       }
  - { key: Q,         mods: Alt,       chars: "\x10q"                       }
  - { key: R,         mods: Alt,       chars: "\x10r"                       }
  - { key: S,         mods: Alt,       chars: "\x10s"                       }
  - { key: T,         mods: Alt,       chars: "\x10t"                       }
  - { key: U,         mods: Alt,       chars: "\x10u"                       }
  - { key: V,         mods: Alt,       chars: "\x10v"                       }
  - { key: W,         mods: Alt,       chars: "\x10w"                       }
  - { key: X,         mods: Alt,       chars: "\x10x"                       }
  - { key: Y,         mods: Alt,       chars: "\x10y"                       }
  - { key: Z,         mods: Alt,       chars: "\x10z"                       }
  - { key: A,         mods: Alt|Shift, chars: "\x10A"                       }
  - { key: B,         mods: Alt|Shift, chars: "\x10B"                       }
  - { key: C,         mods: Alt|Shift, chars: "\x10C"                       }
  - { key: D,         mods: Alt|Shift, chars: "\x10D"                       }
  - { key: E,         mods: Alt|Shift, chars: "\x10E"                       }
  - { key: F,         mods: Alt|Shift, chars: "\x10F"                       }
  - { key: G,         mods: Alt|Shift, chars: "\x10G"                       }
  - { key: H,         mods: Alt|Shift, chars: "\x10H"                       }
  - { key: I,         mods: Alt|Shift, chars: "\x10I"                       }
  - { key: J,         mods: Alt|Shift, chars: "\x10J"                       }
  - { key: K,         mods: Alt|Shift, chars: "\x10K"                       }
  - { key: L,         mods: Alt|Shift, chars: "\x10L"                       }
  - { key: M,         mods: Alt|Shift, chars: "\x10M"                       }
  - { key: N,         mods: Alt|Shift, chars: "\x10N"                       }
  - { key: O,         mods: Alt|Shift, chars: "\x10O"                       }
  - { key: P,         mods: Alt|Shift, chars: "\x10P"                       }
  - { key: Q,         mods: Alt|Shift, chars: "\x10Q"                       }
  - { key: R,         mods: Alt|Shift, chars: "\x10R"                       }
  - { key: S,         mods: Alt|Shift, chars: "\x10S"                       }
  - { key: T,         mods: Alt|Shift, chars: "\x10T"                       }
  - { key: U,         mods: Alt|Shift, chars: "\x10U"                       }
  - { key: V,         mods: Alt|Shift, chars: "\x10V"                       }
  - { key: W,         mods: Alt|Shift, chars: "\x10W"                       }
  - { key: X,         mods: Alt|Shift, chars: "\x10X"                       }
  - { key: Y,         mods: Alt|Shift, chars: "\x10Y"                       }
  - { key: Z,         mods: Alt|Shift, chars: "\x10Z"                       }
  - { key: Key1,      mods: Alt,       chars: "\x101"                       }
  - { key: Key2,      mods: Alt,       chars: "\x102"                       }
  - { key: Key3,      mods: Alt,       chars: "\x103"                       }
  - { key: Key4,      mods: Alt,       chars: "\x104"                       }
  - { key: Key5,      mods: Alt,       chars: "\x105"                       }
  - { key: Key6,      mods: Alt,       chars: "\x106"                       }
  - { key: Key7,      mods: Alt,       chars: "\x107"                       }
  - { key: Key8,      mods: Alt,       chars: "\x108"                       }
  - { key: Key9,      mods: Alt,       chars: "\x109"                       }
  - { key: Key0,      mods: Alt,       chars: "\x100"                       }
  - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  - { key: Grave,     mods: Alt,       chars: "\x10`"                       } # Alt + `
  - { key: Grave,     mods: Alt|Shift, chars: "\x10~"                       } # Alt + ~
  - { key: Period,    mods: Alt,       chars: "\x10."                       } # Alt + .
  - { key: Key8,      mods: Alt|Shift, chars: "\x10*"                       } # Alt + *
  - { key: Key3,      mods: Alt|Shift, chars: "\x10#"                       } # Alt + #
  - { key: Period,    mods: Alt|Shift, chars: "\x10>"                       } # Alt + >
  - { key: Comma,     mods: Alt|Shift, chars: "\x10<"                       } # Alt + <
  - { key: Minus,     mods: Alt|Shift, chars: "\x10_"                       } # Alt + _
  - { key: Key5,      mods: Alt|Shift, chars: "\x10%"                       } # Alt + %
  - { key: Key6,      mods: Alt|Shift, chars: "\x10^"                       } # Alt + ^
  - { key: Backslash, mods: Alt,       chars: "\x10\\"                      } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x10|"                       } # Alt + |
    # Bash
  - { key: Period,   mods: Alt,       chars: "\x10."                       }
  - { key: Key8,     mods: Alt|Shift, chars: "\x10*"                       }
  - { key: Key3,     mods: Alt|Shift, chars: "\x10#"                       }
    # `tmux`
  - { key: Key1,     mods: Alt,     chars: "\x101"                       }
  - { key: Key2,     mods: Alt,     chars: "\x102"                       }
  - { key: Key3,     mods: Alt,     chars: "\x103"                       }
  - { key: Key4,     mods: Alt,     chars: "\x104"                       }
  - { key: Key5,     mods: Alt,     chars: "\x105"                       }
  - { key: Key6,     mods: Alt,     chars: "\x106"                       }
  - { key: Key7,     mods: Alt,     chars: "\x107"                       }
  - { key: Key8,     mods: Alt,     chars: "\x108"                       }
  - { key: Key9,     mods: Alt,     chars: "\x109"                       }
  - { key: Key0,     mods: Alt,     chars: "\x100"                       }
    # Emacs
  - { key: Period,   mods: Alt|Shift, chars: "\x10>"                       } # Alt + >
  - { key: Comma,    mods: Alt|Shift, chars: "\x10<"                       } # Alt + <
