colors:
  primary:
    background: '#211930'
    foreground: '#ffffff'

  normal:
    black:   '#000000'
    red:     '#9D571A'
    green:   '#75FF95'
    yellow:  '#E5E64B'
    blue:    '#87AFDF'
    magenta: '#C978EB'
    cyan:    '#00AFAF'
    white:   '#FFFFFF'

  cursor:
    text: '0xffffff'
    cursor: '#456954'

  bright:
    black:   '#555555'
    red:     '#DABDBD'
    green:   '#BDDABD'
    yellow:  '#DADABD'
    blue:    '#3792E3'
    magenta: '#D751FF'
    cyan:    '#00FFFF'
    white:   '#999999'

