[colors.bright]
black = "#8B8680" # Middle Grey
blue = "#87AFDF"
cyan = "#00FFFF"
green = "#BDDABD"
magenta = "#DBA3EB"
red = "#DABDBD"
white = "#CCCCCC"
yellow = "#AAAA00"

[colors.normal]
black = "#000000"
blue = "#95a7cd"
cyan = "#00AFAF"
green = "#6FCA70"
magenta = "#C978EB"
red = "#DB7B34"
white = "#FFFFFF"
yellow = "#BBBB00"
