[colors.bright]
black = "#808080"
blue = "#87AFDF"
cyan = "#00FFFF"
green = "#BDDABD"
magenta = "#DBA3EB"
red = "#DABDBD"
white = "#CCCCCC"
yellow = "#AAAA00"

[colors.normal]
black = "#000000"
blue = "#3792E3"
cyan = "#00AFAF"
green = "#6FCA70"
magenta = "#C978EB"
red = "#AA5511"
white = "#FFFFFF"
yellow = "#BBBB00"
