[colors.primary]
# Kleene Purple 1
# background = "#211930"
# Kleene Purple 2
# background = "#2B233D"
# Kleene Purple 3
# background = "#2A233C"
# BBEdit Black
# background = "#141414"
# Xcode Black
# background = "#292A30"
# Black
# Don't use pure black because otherwise the lower right window corner won't be
# visible when overlapping
background = "#141414"
# Text Color
foreground = "#FFFFFF"

[colors.cursor]
cursor = "#00BB00"
text = "0xFFFFFF"

[colors.normal]
black = "#000000"
red = "#FF8787"
green = "#87FF87"
yellow = "#FFFF00"
blue = "#87AFFF"
magenta = "#FF87FF"
cyan = "#00FFFF"
white = "#FFFFFF"

[colors.bright]
black = "#878787"
red = "#FFAF87"
green = "#D7FF87"
yellow = "#FFFFD7"
blue = "#D7FFFF"
magenta = "#FFAFFF"
cyan = "#5FFFFF"
white = "#D7D7D7"
