# Shell
brew 'zsh'
brew 'git'
brew 'tig'
brew 'fzf'
brew 'tmux'
brew 'ripgrep'
brew 'fd'
brew 'bat'
# Support for `incsearch`
brew 'less'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
# Modern
# brew 'nushell'
# brew 'fish'
# brew 'helix'

# Editor
brew 'aspell'
brew 'neovim'
brew 'vim'
brew 'editorconfig'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Swift
# Objective-C
brew 'carthage'
brew 'clang-format'
# MIDI
# Go
brew 'go'
brew 'jq'
# Rust
brew 'wasm-pack'
brew 'rust-analyzer'
# lua
brew 'lua-language-server'
# Markdown
brew 'marksman'

# Special
brew 'pandoc'
brew 'gh'
brew 'cloc'
brew 'ncdu'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'youtube-dl'
brew 'mitmproxy'
brew 'hyperfine'
# Shows whitespace nicer than xxd
brew 'hexyl'

# macOS
brew 'suspicious-package'

# Cask GUI Apps
tap 'homebrew/cask'
cask 'blender'
cask 'godot'
cask 'anki'
cask 'alacritty'
cask 'processing'

# Media
brew 'ffmpeg'
brew 'imagemagick'

# Games
brew 'nethack'
