# Shell
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'fish'
brew 'git'
brew 'tig'
brew 'tmux'
brew 'fasd'
brew 'ripgrep'
brew 'fd'
brew 'bat'
brew 'mas'
brew 'rename'
# Support for `lesskey`
brew 'less'
brew 'wget'

# Editor
brew 'aspell'
# Required before `ctags`
brew 'svn'
# Head version of `ctags` contains support for Objective-C
brew 'ctags', args: ['HEAD']
brew 'vim'
brew 'neovim'
brew 'editorconfig'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Shell
brew 'shfmt'
brew 'shellcheck'
# Swift
brew 'carthage'
brew 'swiftlint'
brew 'swiftformat'
# Objective-C
brew 'clang-format'
# MIDI
brew 'midicsv'
# C
# Failing on Apple Silicon
# tap 'LouisBrunner/valgrind'
# brew 'LouisBrunner/valgrind/valgrind', args: ['HEAD']
# Lisp
brew 'sbcl'
# Go
brew 'go'
brew 'jq'
# Rust
brew 'wasm-pack'

# Special
brew 'pandoc'
brew 's3cmd'
brew 'gnu-typist'
brew 'figlet'
brew 'w3m'
brew 'hub'
brew 'gh'
brew 'cloc'
brew 'id3lib'
brew 'ledger'
brew 'ncdu'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'youtube-dl'
brew 'wdiff'
brew 'mitmproxy'
brew 'neofetch'

# Railwaycat
# tap 'railwaycat/emacsmacport'
# brew 'emacs-mac'
# The `with-no-frame-refocus` options on this version of Emacs fixes the issue
# of switching spaces when the last Emacs window on a space closes.
# Note after installing run `brew info emacs-plus` for the command to symlink
# to applications
tap 'd12frosted/emacs-plus'
brew 'emacs-plus', args: ['with-elrumo2-icon', 'with-no-frame-refocus']

# Cask GUI Apps
tap 'homebrew/cask'
# cask 'emacs'
cask 'blender'
cask 'anki'
cask 'kitty'
cask 'alacritty'

# Animated GIFs, `gifify` dependencies
brew 'ffmpeg'
brew 'imagemagick'

# Ergodox & Planck
brew 'qmk/qmk/qmk'
tap 'osx-cross/avr'
tap 'osx-cross/arm'
tap 'qmk/qmk'

# Unity
# Disable these because they fail too often when installing
# These packages are required to get autocomplete working with the C# VS Code
# extension from Microsoft
# (This also requires `"omnisharp.useGlobalMono": "always"` be set in VS Code's
# preferences)
# brew 'mono'
# brew 'dotnet'
# Mono & Dotnet dependencies
# brew 'brotli'
# brew 'libssh2'
# brew 'zstd'
# brew 'libmetalink'
# brew 'openldap'
# brew 'curl'

# Games
brew 'nethack'

# Dependencies

# Common Dependencies
brew 'openssl'
brew 'pcre'
brew 'readline'
brew 'xz'
brew 'gmp'
brew 'libffi'

# Vim
brew 'lua'
# Ruby
brew 'libyaml'
# Tmux
brew 'libevent'
# renameutils
brew 'coreutils'
# ffmpeg
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'gettext'
brew 'x264'
brew 'lame'
brew 'xvid'
# imagemagick
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
# Legder
brew 'boost'
# w3m
brew 'bdw-gc'
# mkvtoolnix / mkvtomp4
brew 'fmt'
brew 'guile'
brew 'libmagic'
brew 'mkvtoolnix'
brew 'gpac'
brew 'libebml'
brew 'libmatroska'
brew 'mkvtomp4'

# NeoVim
brew 'cmake'
brew 'libbsd'
brew 'libnsl'
brew 'libuv'
brew 'luv'
brew 'neovim'
brew 'utf8proc'
brew 'icu4c'
brew 'libmetalink'
brew 'unibilium'
brew 'libvterm'
brew 'msgpack'
brew 'ninja'
brew 'libmd'
brew 'libtirpc'
brew 'libtermkey'
brew 'luajit-openresty'
brew 'tree-sitter'
brew 'pcre'
