" set guifont=Berkeley\ Mono:h13
" set guifont=Consolas:h14
" This looks slightly more readable on Retina displays
set guifont=SF\ Mono\ Medium:h13
" set guifont=SF\ Mono:h13
set linespace=2

" Disable audible bell
autocmd GUIEnter * set vb t_vb=

" Don't use GUI tabs
set guioptions-=e

" Background & Cursor
" set background=light
" BBEdit Dark
highlight NonText guibg=#141414
highlight Normal guibg=#141414
highlight Cursor guibg=#00BB00
augroup override_guicolors
  autocmd!
  autocmd ColorScheme * highlight NonText guibg=#141414
  autocmd ColorScheme * highlight Normal guibg=#141414
  autocmd ColorScheme * highlight Cursor guibg=#00BB00
augroup END

" Setting the cursor color has to be after setting the theme
set guicursor=a:blinkon0

" Env
let $MANPATH = expand('~/.brew/share/man') . ':' . expand('~/.man') . ':' . expand('~/.man-local') . ':' . $MANPATH
let $RIPGREP_CONFIG_PATH= expand('~/.ripgreprc')

" There's an oddity in Vim, if you try this sequence:
" 1. `vim -u NONE`
" 2. `setlocal spell`
" 3. `enew`
" 4. `setlocal spell?`
" Note that spelling is *enabled* in the new buffer, this is because it seems
" like the existing buffer is partly re-used if it's empty.
" E.g., this behavior doesn't happen if `:new` is used instead of `:enew`, or
" if the first buffer is modified before trying `:enew`.
" Enabling this exasperates this oddity because it means Markdown specific
" settings get inhereted, leading to unexpected behavior.
" Trying this only in `gvimrc`
" The problem is then taking log output and pasting it into a Vim buffer will
" then have markdown filetype.
" augroup default_new_buffer_filetype
"   autocmd!
"   autocmd BufWinEnter *
"         \ if &buftype ==# ''
"         \ && &filetype ==# ''
"         \ && bufname('%') ==# ''
"         \ && line('$') == 1
"         \ && getline(1) ==# ''
"         \ | setlocal filetype=markdown
"         \ | endif
" augroup END
