" set guifont=Berkeley\ Mono:h13
" set guifont=Consolas:h14
" set guifont=SF\ Mono\ Medium:h13
set guifont=SF\ Mono:h13
set linespace=2

" Disable audible bell
autocmd GUIEnter * set vb t_vb=

let $MANPATH = expand('~/.brew/share/man') . ':' . expand('~/.man') . ':' . expand('~/.man-local') . ':' . $MANPATH
let $RIPGREP_CONFIG_PATH= expand('~/.ripgreprc')

" Background
" set background=light
" BBEdit Dark
highlight NonText guibg=#141414
highlight Normal guibg=#141414
augroup override_colors
  autocmd!
  autocmd ColorScheme * highlight NonText guibg=#141414
  autocmd ColorScheme * highlight Normal guibg=#141414
augroup END

set guicursor=a:blinkon0
" Setting the cursor color has to be after setting the theme
highlight Cursor guibg=#00BB00
