#!/usr/bin/env sh

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper

# Must be after plugin helper
# + for next
# CTX=+
# current context
export CUR_CTX=1

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

result="$PWD/$(~/.bin/z_subdir_fzf)"

if [ ! -d "$result" ]; then
  exit 0
fi

nnn_cd "$result" "$CTX"
