#!/usr/bin/env sh

CTX=+

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

result="$PWD/$(~/.bin/z_fzf_subdir)"

if [ ! -d "$result" ]; then
  exit 0
fi

nnn_cd "$result" "$CTX"
