#!/usr/bin/env sh

CTX=+

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

result="$(~/.bin/ls_fzf)"

if [ -n "$result" ]; then
    exit 1
fi

if [ -d "$result" ]; then
    nnn_cd "$result" "$CTX"
elif [ -f "$result" ]; then
    exec "$EDITOR" "$result"
fi

