#!/usr/bin/env sh

if [ -z "$1" ]; then
    exit 1
fi

if [ -d "$1" ]; then
    find "$1" | less
elif [ -f "$1" ]; then
    if command -v bat &> /dev/null; then
        # Use the simple `--style=header` which doesn't include line numbers
        # Line numbers intefere with copying text from the previewed file
        bat --paging=always "$1"
    else
        cat "$1" | less
    fi
fi
