#!/usr/bin/env sh

if [ -z "$1" ]; then
    exit 1
fi

if [ -d "$1" ]; then
    find "$1" | less
elif [ -f "$1" ]; then
    if command -v bat &> /dev/null; then
        bat --paging=always "$1"
    else
        cat "$1" | less
    fi
fi
