(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#000000" "#D32D1E" "#62D63F" "#E5E64B" "#005FFF" "#af00df" "#4AA4B0" "#ffffff"])
 '(custom-safe-themes
   '("ca9ce9f0c5bb46610c20f4ebcaa3d1c8ed6b8f9c5a956620cba250686fe645cf" "f82e68d489e6c21c9552c4e8e35a03d126d9eba632a8e7b4f9329d1374b4a19c" "ad114fd8820edf7d947f356a237468ae2c402565a60b813ee36f6cd3f1d325ae" "c6fb2c37975e0d8fcc91ae7501f06bc9c58f3fb55e658be0fce30cd58bd66f3e" default))
 '(package-selected-packages
   '(bind-map pbcopy rainbow-delimiters fill-column-indicator evil-smartparens lua-mode typescript-mode magit eshell-syntax-highlighting monky better-defaults yaml-mode embark-consult kotlin-mode consult ef-themes rust-mode eglot evil-goggles use-package nodejs-repl csv-mode ledger-mode fish-mode markdown-mode swift-mode inf-ruby enh-ruby-mode slime smartparens rainbow-mode yasnippet editorconfig magit-filenotify wgrep jade-mode aggressive-indent page-break-lines expand-region adaptive-wrap vundo vertico orderless marginalia evil-visualstar evil-surround evil-numbers evil-commentary corfu corfu-terminal diminish cape evil-terminal-cursor-changer popon org-modern modus-themes company))
 '(vc-annotate-color-map
   '((20 . "#F92672")
     (40 . "#CF4F1F")
     (60 . "#C26C0F")
     (80 . "#E6DB74")
     (100 . "#AB8C00")
     (120 . "#A18F00")
     (140 . "#989200")
     (160 . "#8E9500")
     (180 . "#A6E22E")
     (200 . "#729A1E")
     (220 . "#609C3C")
     (240 . "#4E9D5B")
     (260 . "#3C9F79")
     (280 . "#A1EFE4")
     (300 . "#299BA6")
     (320 . "#2896B5")
     (340 . "#2790C3")
     (360 . "#66D9EF")))
 '(vc-annotate-very-old-color nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bold ((t (:bold t))))
 '(evil-goggles-default-face ((t (:inherit region))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#808080" :slant oblique))))
 '(font-lock-comment-face ((t (:foreground "#808080" :slant oblique))))
 '(git-commit-summary ((t (:inherit rk-text :foreground nil :background unspecified))))
 '(italic ((t (:underline nil :slant italic))))
 '(markdown-blockquote-face ((t (:inherit default :foreground nil))))
 '(markdown-bold-face ((t (:inherit rk-text :foreground nil :background unspecified :bold t))))
 '(markdown-code-face ((t (:inherit rk-comment :foreground nil :background unspecified))))
 '(markdown-footnote-marker-face ((t (:inherit rk-comment :slant normal))))
 '(markdown-gfm-checkbox-face ((t (:inherit rk-comment :foreground nil))))
 '(markdown-header-delimiter-face ((t (:inherit rk-comment :foreground nil))))
 '(markdown-header-face-1 ((t (:inherit rk-header :foreground nil))))
 '(markdown-header-face-2 ((t (:inherit rk-header :foreground nil))))
 '(markdown-header-face-3 ((t (:inherit rk-header :foreground nil))))
 '(markdown-header-face-4 ((t (:inherit rk-header :foreground nil))))
 '(markdown-header-face-5 ((t (:inherit rk-header :foreground nil))))
 '(markdown-header-face-6 ((t (:inherit rk-header :foreground nil))))
 '(markdown-inline-code-face ((t (:inherit markdown-pre-face :foreground nil :background unspecified))))
 '(markdown-italic-face ((t (:inherit rk-text :foreground nil :background unspecified))))
 '(markdown-link-face ((t (:inherit rk-link :foreground nil))))
 '(markdown-list-face ((t (:inherit rk-text2))))
 '(markdown-markup-face ((t (:inherit rk-comment :foreground nil))))
 '(markdown-pre-face ((t (:inherit rk-comment :foreground nil :background unspecified))))
 '(markdown-url-face ((t (:inherit rk-comment :foreground nil))))
 '(nobreak-space ((t (:inherit rk-whitespace :background nil :underline nil))))
 '(org-agenda-date ((t (:inherit rk-header :foreground nil))))
 '(org-code ((t (:inherit rk-comment :foreground nil))))
 '(org-level-1 ((t (:inherit rk-text2 :foreground nil))))
 '(org-level-2 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-3 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-4 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-5 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-6 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-7 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-level-8 ((t (:inherit org-level-1 :foreground nil :bold nil))))
 '(org-property-value ((t (:inherit rk-comment :foreground nil))))
 '(org-special-keyword ((t (:inherit rk-comment :bold t :foreground nil))))
 '(rk-bold ((t (:inherit rk-header))))
 '(rk-callout ((t (:background "#303030"))))
 '(rk-change ((t (:foreground "#3792E3"))))
 '(rk-change-highlight ((t (:background "#3792E3"))))
 '(rk-comment ((t (:foreground "#808080"))))
 '(rk-diff-add ((t (:inherit rk-success))))
 '(rk-diff-change ((t (:inherit rk-change))))
 '(rk-diff-remove ((t (:inherit rk-error :underline nil))))
 '(rk-error ((t (:foreground "#9D571A" :underline t))))
 '(rk-error-highlight ((t (:background "#9D571A"))))
 '(rk-header ((t (:foreground "#eeeeee" :bold t))))
 '(rk-highlight ((t (:background "#5f0087"))))
 '(rk-highlight-line ((t (:background "#3a3a3a"))))
 '(rk-italic ((t (:inherit rk-text :slant oblique))))
 '(rk-link ((t (:foreground "#87AFDF" :underline t))))
 '(rk-match ((t (:background "#5f0087"))))
 '(rk-modeline-active ((t (:foreground "#ffffff" :background "#808080"))))
 '(rk-modeline-inactive ((t (:foreground "#b2b2b2" :background "#4e4e4e"))))
 '(rk-none ((t (:foreground nil :background nil :bold nil :underline nil))))
 '(rk-popup-match ((t (:foreground "#87AFDF"))))
 '(rk-popup-selection ((t (:inherit rk-match))))
 '(rk-prompt ((t (:inherit rk-match :bold t))))
 '(rk-search ((t (:background "#822EB6" :foreground "#ffffff"))))
 '(rk-string ((t (:foreground "#75FF95"))))
 '(rk-success ((t (:foreground "#75FF95"))))
 '(rk-tag-active ((t (:inherit rk-modeline-active :bold t))))
 '(rk-tag-inactive ((t (:inherit rk-modeline-inactive :bold t))))
 '(rk-text ((t (:foreground "#eeeeee"))))
 '(rk-text2 ((t (:foreground "#b2b2b2"))))
 '(rk-warning ((t (:foreground "#E5E64B" :underline t))))
 '(rk-warning-highlight ((t (:background "#E5E64B" :foreground "#000000" :bold t))))
 '(rk-whitespace ((t (:inherit rk-highlight-line))))
 '(show-paren-match ((t (:underline t :background unspecified :foreground nil :bold t))))
 '(show-paren-mismatch ((t (:inherit rk-error))))
 '(trailing-whitespace ((t (:inherit rk-whitespace :background unspecified :underline nil))))
 '(whitespace-line ((t (:inherit rk-warning :background unspecified))))
 '(whitespace-space-after-tab ((t (:inherit rk-whitespace :background unspecified :underline nil))))
 '(whitespace-space-before-tab ((t (:inherit rk-whitespace :background unspecified :underline nil))))
 '(whitespace-tab ((t (:inherit rk-whitespace :background unspecified :underline nil)))))
