# Shell
brew 'git'
brew 'gitui'
brew 'fzf'
brew 'tmux'
brew 'ripgrep'
# Installation of `fd`, `bat`, and `weechat` is failing
brew 'fd'
brew 'bat'
brew 'ncdu'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
brew 'universal-ctags'

# Editor
brew 'aspell', args: ['with-lang-en']
brew 'emacs'
brew 'editorconfig'
brew 'vim'
brew 'neovim'
brew 'gh'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'hyperfine'

# Special
brew 'pandoc'
# Shows whitespace nicer than xxd
brew 'hexyl'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Shell
# Rust
brew 'wasm-pack'
brew 'rust-analyzer'
# C
# brew 'valgrind'
# C++
brew 'cmake'
# json
brew 'jq'
brew 'lua-language-server'
# C++
# Also installs `clangd`, `clang`, `lldb`, `lldb-vscode`
# Removed to save disk space
# brew 'llvm'
# Markdown
# On Linux this gets:
# error while loading shared libraries: libgcc_s.so.1: cannot open shared
# object file: No such file or directory Work around is to do `sudo find /
# -iname *libraryname*.so*` to find the library path, then Update it like
# `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib/x86_64-linux-gnu` and export
# `LD_LIBRARY_PATH`
brew 'marksman'

# Games
brew 'nethack'
