# Shell
brew 'git'
brew 'tig'
brew 'tmux'
brew 'ripgrep'
brew 'fd'
brew 'eza'
brew 'ncdu'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
brew 'universal-ctags'
# Support `--incsearch`
# Note that this also requires adding `--RAW-CONTROL-CHARS` to `$LESS` to fix
# colors (otherwise they show up as escape sequences)
brew 'less'
brew 'gnu-typist'
brew 'gh'

# Editor
brew 'aspell'
brew 'emacs'
brew 'editorconfig'
brew 'vim'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']

# Special
brew 'pandoc'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Shell
# C
# brew 'valgrind'
# C++
brew 'cmake'
# json
brew 'jq'
# C++
# Also installs `clangd`, `clang`, `lldb`, `lldb-vscode`
# Removed to save disk space
# brew 'llvm'

# Games
brew 'nethack'
