# Shell
brew 'git'
brew 'tig'
brew 'fzf'
brew 'tmux'
brew 'ripgrep'
# Installation of `fd`, `bat`, and `weechat` is failing
brew 'fd'
brew 'bat'
# `less` support for `incsearch`
brew 'less'
brew 'ncdu'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
# Modern
brew 'helix'
brew 'nushell'
brew 'fish'

# Editor
brew 'aspell', args: ['with-lang-en']
brew 'emacs'
brew 'editorconfig'
brew 'vim'
brew 'neovim'
brew 'gh'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'hyperfine'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Shell
# Rust
brew 'wasm-pack'
brew 'rust-analyzer'
# C
# brew 'valgrind'
# C++
brew 'cmake'
# json
brew 'jq'
brew 'lua-language-server'
# C++
# Also installs `clangd`, `clang`, `lldb`, `lldb-vscode`
# Removed to save disk space
# brew 'llvm'
# Markdown
# On Linux this gets:
# error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
# brew 'marksman'

# Games
brew 'nethack'
