# Shell
brew 'tig'
brew 'tree'
brew 'ripgrep'
brew 'fd'
brew 'fzf'
brew 'bat'
# Support for `lesskey`
brew 'less'
brew 'ncdu'
brew 'hub'
brew 'gh'

# Shell
brew 'shfmt'
brew 'shellcheck'

# hub
brew 'util-linux'
