# Shell
brew 'zsh'
brew 'git'
brew 'gitui'
brew 'fzf'
brew 'tmux'
brew 'ripgrep'
brew 'fd'
brew 'bat'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
brew 'universal-ctags'

# Editor
brew 'aspell'
# Dependency of jinx spell checker in Emacs
# brew 'enchant'
brew 'vim'
brew 'nvim'
brew 'editorconfig'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Shell
# Swift
# Objective-C
brew 'carthage'
brew 'fastlane'
brew 'clang-format'
# Go
brew 'go'
# json
brew 'jq'
# lua
brew 'lua-language-server'
# rust
brew 'rust-analyzer'
# Markdown
brew 'marksman'

# Special
brew 'pandoc'
brew 'gh'
brew 'cloc'
brew 'ncdu'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'youtube-dl'
brew 'mitmproxy'
brew 'hyperfine'
# Shows whitespace nicer than xxd
brew 'hexyl'
brew 'scrcpy'

# VR

# macOS
brew 'suspicious-package'

# Cask GUI Apps
tap 'homebrew/cask'
# cask 'emacs'
cask 'blender'
cask 'godot'
cask 'alacritty'

# Animated GIFs, `gifify` dependencies
brew 'ffmpeg'
brew 'imagemagick'
