# Shell
brew 'zsh'
brew 'git'
brew 'tig'
brew 'ripgrep'
# Definitely need for remote servers
brew 'tmux'
brew 'fd'
brew 'zoxide'
brew 'nnn'
# Really useful to see diff by word quickly
brew 'git-delta'
brew 'universal-ctags'
brew 'gnu-typist'

# Editor
brew 'vim'
brew 'editorconfig'

# Languages
# JavaScript
# Do not use homebrew `nvm` because it overrides `NVM_DIR` which causes issues.
# Instead install `nvm` directly.
# Ruby
brew 'chruby'
brew 'ruby-install'
# Swift
# Objective-C
brew 'carthage'
# Go
brew 'go'
# json
brew 'jq'
# Ruby
# Some gems fail to install without `coreutils`
brew 'coreutils'

# Special
brew 'pandoc'
brew 'gh'
brew 'cloc'
brew 'ncdu'
# HEAD for truecolor support
brew 'mosh', args: ['HEAD']
brew 'yt-dlp'
# VR
# Use another install method
# brew 'scrcpy'
# `-g, --chgexit`: Watch a command until its output changes, e.g., `watch -g
# "adb devices"`
brew 'watch'

# Cask GUI Apps
tap 'homebrew/cask'
cask 'blender'
cask 'anki'
cask 'alacritty'
cask 'processing'
cask 'dosbox-staging'
cask 'gzdoom'
cask 'suspicious-package'

# Media
brew 'ffmpeg'
brew 'imagemagick'

# Games
brew 'nethack'
