# The session name gets cutoff too easily without this
set -g status-left-length 40

# Make status right prefix
set -g status-right '#{?#{SSH_CONNECTION},#H,}#{?client_prefix, -- PREFIX --,}'

# Just bold
set -g window-status-current-style fg=default,bold


# Active
setw -g window-active-style fg=terminal,bg=terminal
# Inactive
setw -g window-style fg=colour250,bg=colour234

run-shell "~/.bin/nobin/_tmux-set-ssh-status.sh"
