# The session name gets cutoff too easily without this
set -g status-left-length 40

# Make status right prefix
# `#{S:#{W:...}}` loops every window to show a `!` if any window has a bell
# (E.g., if we have too many windows and the one with a bell isn't visible)
# Leading space to separate from `>` indicating more windows 
# (Without this we get `>aresdev` when there are too many windows)
set -g status-right ' #{?#{S:#{W:#{?window_bell_flag,!,}}},#[reverse]!#[default] ,}#{?#{SSH_CONNECTION},#H,}#{?client_prefix, -- PREFIX --,}'

# Just bold
set -g window-status-current-style fg=default,bold


# Active
setw -g window-active-style fg=terminal,bg=terminal
# Inactive
setw -g window-style fg=colour250,bg=colour235
